### ISSUE TITLE
Would love to take over maintainence...

### ISSUE THREAD

**Issue by polygoncount** [alicia86/roll20-character-sheets#12]
...but I don't know what I'm doing. Sorry if this isn't the accepted way of doing this, I tried contacting you on Roll20 some time ago with no response.

Any tips?

**Comment by alicia86** [comment]
Hi Polygoncount, I'm not seeing the message you sent (maybe under a different name?)
Please feel free to message me on discord: AliciaGD#4971

**Comment by polygoncount** [comment]
Discord friend request sent!
